name: Build macOS-X64

on:
  push:
    branches: [dev]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build macos
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: "Install Homebrew"
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: "Install required packages."
        run: |
          brew update
          brew install libomp

      - name: "Build"
        run: |
          rm -rf build 
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXE=OFF -DCMAKE_CXX_COMPILER=g++-11
          cmake --build build
